services:
  # Production service - optimized build
  app:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
      - "7860:7860"
    environment:
      APP_PORT: 8000
      WS_PORT: 7860
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN:-}
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 512m
    restart: unless-stopped

  # Development service - super fast startup with local .venv
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      # Mount entire project for hot reload
      - .:/app
      # This is the key: mount your local .venv
      - ./.venv:/app/.venv:cached
    environment:
      APP_PORT: 8000
      WS_PORT: 7860
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      FLASK_ENV: development
      GRADIO_SERVER_NAME: 0.0.0.0
      HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN:-}
      PDM_VENV_IN_PROJECT: 1
    profiles:
      - dev
    user: "1000:1000"